version: '3'
name: docker-ai-chatbot
services:
  streamlit:
    image: python:latest
    ports:
      - '8502:8501'
    networks:
      - internal-net
    volumes:
      - ./chat:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run chat.py"
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    networks:
      - internal-net
    volumes:
      - ./llm:/root/.ollama
    restart: unless-stopped

networks:
  internal-net:
    driver: bridge
  
